import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 p-4 text-white">
          <h1 className="text-2xl font-bold">Next Travelo</h1>
        </header>

        {children}

        <footer className="bg-gray-800 text-white p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
