import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['100', '300', '400', '500', '700', '900',],
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <header className="bg-gray-800 p-4 text-white">
          <h1 className="text-2xl font-bold font-montserrat">Montserrat</h1>
        </header>

        {children}

        <footer className="bg-gray-800 text-white p-4 font-roboto font-bold text-2xl">
          <p>Roboto</p>
        </footer>
      </body>
    </html>
  );
}
